import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

/**
 * Generates a synthetic GoCalma clinical note with realistic PII.
 * Used as a demo document for hackathon judges — all data is fictitious.
 */
export async function generateDemoPdf(): Promise<File> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  // ── Page 1: Patient intake form ─────────────────────────────────────────
  const p1 = pdfDoc.addPage([595, 842])
  const { height } = p1.getSize()
  let y = height - 52

  const draw = (page: ReturnType<typeof pdfDoc.addPage>, text: string, opts?: {
    f?: typeof font; size?: number; x?: number; color?: ReturnType<typeof rgb>
  }) => {
    page.drawText(text, {
      x: opts?.x ?? 60,
      y,
      size: opts?.size ?? 10.5,
      font: opts?.f ?? font,
      color: opts?.color ?? rgb(0.1, 0.1, 0.1),
    })
    y -= (opts?.size ?? 10.5) + 7
  }

  const rule = (page: ReturnType<typeof pdfDoc.addPage>) => {
    page.drawLine({ start: { x: 60, y }, end: { x: 535, y }, thickness: 0.5, color: rgb(0.75, 0.75, 0.75) })
    y -= 12
  }

  const gap = (n = 1) => { y -= 9 * n }

  // Header
  draw(p1, 'GoCalma Mental Wellness Clinic', { f: bold, size: 15, color: rgb(0.05, 0.45, 0.35) })
  draw(p1, 'PATIENT CONSULTATION REPORT · STRICTLY CONFIDENTIAL', { size: 9, color: rgb(0.5, 0.5, 0.5) })
  gap(0.5)
  rule(p1)

  // Patient info
  draw(p1, 'PATIENT INFORMATION', { f: bold, size: 11 })
  gap(0.3)
  draw(p1, 'Full name:              Sophie Laurent', { x: 80 })
  draw(p1, 'Date of birth:          14.03.1982', { x: 80 })
  draw(p1, 'AHV / AVS number:       756.1234.5678.97', { x: 80 })
  draw(p1, 'Address:                Bahnhofstrasse 42, 8001 Zürich, Switzerland', { x: 80 })
  draw(p1, 'Mobile:                 +41 79 123 45 67', { x: 80 })
  draw(p1, 'Email:                  sophie.laurent@gmail.com', { x: 80 })
  gap()

  // Insurance
  rule(p1)
  draw(p1, 'INSURANCE & BILLING', { f: bold, size: 11 })
  gap(0.3)
  draw(p1, 'Insurer:                Swica Krankenversicherung AG', { x: 80 })
  draw(p1, 'Policy number:          SW-2026-887441', { x: 80 })
  draw(p1, 'IBAN (reimbursement):   CH56 0483 5012 3456 7800 9', { x: 80 })
  gap()

  // Consultation
  rule(p1)
  draw(p1, 'CONSULTATION: 2026-03-15', { f: bold, size: 11 })
  gap(0.3)
  draw(p1, 'Attending:              Dr. Martin Frei, MD  (Psychiatry, License CH-BE-4421)', { x: 80 })
  gap(0.5)
  draw(p1, 'Patient Sophie Laurent presents with generalised anxiety disorder (ICD-10 F41.1)', { x: 80, size: 10 })
  draw(p1, 'and mild depressive episodes. Reports disrupted sleep patterns since January 2026.', { x: 80, size: 10 })
  draw(p1, 'No current suicidal ideation. PHQ-9 score: 11 (moderate depression).', { x: 80, size: 10 })
  gap(0.5)
  draw(p1, 'Prescription:           Sertraline 50 mg daily (titrate to 100 mg after 4 weeks)', { x: 80 })
  draw(p1, 'Follow-up:              2026-04-12 at 14:00, GoCalma Clinic, Zürich', { x: 80 })
  gap()

  // Referral
  rule(p1)
  draw(p1, 'REFERRAL', { f: bold, size: 11 })
  gap(0.3)
  draw(p1, 'Referred to:            Dr. Amara Osei, Certified CBT Therapist', { x: 80 })
  draw(p1, 'Contact:                amara.osei@cbt-zuerich.ch  ·  +41 44 987 65 43', { x: 80 })
  draw(p1, 'Urgency:                Routine (appointment within 4 weeks)', { x: 80 })
  gap()

  // Footer
  rule(p1)
  draw(p1, 'This document contains special-category personal data (health data) under GDPR Art. 9', { size: 8.5, color: rgb(0.45, 0.45, 0.45) })
  draw(p1, 'and Swiss FADP Art. 5(c). Unauthorised disclosure may result in fines up to CHF 250,000.', { size: 8.5, color: rgb(0.45, 0.45, 0.45) })
  draw(p1, 'Generated by GoCalma EMR v4.2 · Report ID: GC-2026-03-15-00847', { size: 8.5, color: rgb(0.6, 0.6, 0.6) })

  // ── Page 2: Emergency contact + billing address ──────────────────────────
  const p2 = pdfDoc.addPage([595, 842])
  y = height - 52

  draw(p2, 'GoCalma Mental Wellness Clinic', { f: bold, size: 15, color: rgb(0.05, 0.45, 0.35) })
  draw(p2, 'SUPPLEMENTARY DETAILS · Page 2 of 2', { size: 9, color: rgb(0.5, 0.5, 0.5) })
  gap(0.5)
  rule(p2)

  draw(p2, 'EMERGENCY CONTACT', { f: bold, size: 11 })
  gap(0.3)
  draw(p2, 'Name:                   Jean-Paul Laurent (spouse)', { x: 80 })
  draw(p2, 'Phone:                  +41 79 456 78 90', { x: 80 })
  draw(p2, 'Email:                  jp.laurent@bluewin.ch', { x: 80 })
  draw(p2, 'Address:                Bahnhofstrasse 42, 8001 Zürich', { x: 80 })
  gap()

  rule(p2)
  draw(p2, 'PREVIOUS TREATMENT HISTORY', { f: bold, size: 11 })
  gap(0.3)
  draw(p2, 'Patient was previously treated by Dr. Clara Huber, Psychiatry, Bern (2023–2024).', { x: 80, size: 10 })
  draw(p2, 'Diagnosis at that time: Burnout syndrome (ICD-10 Z73.0). Patient responded well to CBT.', { x: 80, size: 10 })
  draw(p2, 'No prior hospitalisation. No known medication allergies.', { x: 80, size: 10 })
  gap()

  rule(p2)
  draw(p2, 'BILLING ADDRESS', { f: bold, size: 11 })
  gap(0.3)
  draw(p2, 'Sophie Laurent', { x: 80 })
  draw(p2, 'Bahnhofstrasse 42', { x: 80 })
  draw(p2, '8001 Zürich', { x: 80 })
  draw(p2, 'Switzerland', { x: 80 })
  gap()
  draw(p2, 'Invoice total:          CHF 320.00 (covered by Swica, excess CHF 50.00)', { x: 80 })
  draw(p2, 'Credit card on file:    4111 1111 1111 1111  (Visa, expires 09/28)', { x: 80 })
  gap()

  rule(p2)
  draw(p2, 'CONSENT & SIGNATURES', { f: bold, size: 11 })
  gap(0.3)
  draw(p2, 'I, Sophie Laurent (DOB 14.03.1982), consent to the processing of my health data', { x: 80, size: 10 })
  draw(p2, 'for the purpose of treatment and billing in accordance with the Swiss FADP.', { x: 80, size: 10 })
  gap(0.5)
  draw(p2, 'Patient signature:      _______________________     Date: 2026-03-15', { x: 80, size: 10 })
  draw(p2, 'Clinician signature:    _______________________     Dr. Martin Frei', { x: 80, size: 10 })

  const bytes = await pdfDoc.save()
  return new File([bytes.buffer as ArrayBuffer], 'demo-patient-report.pdf', { type: 'application/pdf' })
}

/**
 * Generates a scanned-style CV with Anya's photo.
 * The entire page is rendered to a canvas → PNG → embedded as an image in the PDF.
 * Because there is no text layer, requiresOCR fires and Tesseract reads the text.
 * Used to demo OCR at the hackathon.
 */
export async function generateOCRDemoPdf(): Promise<File> {
  // Landscape A4 — feels like a phone photo of an ID on a desk
  const W = 1123
  const H = 794

  const canvas = new OffscreenCanvas(W, H)
  const ctx = canvas.getContext('2d')
  if (!ctx) throw new Error('OffscreenCanvas 2D context unavailable')

  // ── Phone background (desk/table feel) ──────────────────────────────────
  ctx.fillStyle = '#d6d3ce'
  ctx.fillRect(0, 0, W, H)
  // subtle texture via noise-like dots
  ctx.fillStyle = 'rgba(0,0,0,0.04)'
  for (let i = 0; i < 800; i++) {
    ctx.fillRect(Math.random() * W, Math.random() * H, 2, 2)
  }

  // ── ID card — centered, slight shadow ───────────────────────────────────
  const CX = 80   // card left
  const CY = 90   // card top
  const CW = 960  // card width
  const CH = 610  // card height
  const R  = 18   // corner radius

  // Shadow
  ctx.shadowColor = 'rgba(0,0,0,0.35)'
  ctx.shadowBlur = 28
  ctx.shadowOffsetX = 6
  ctx.shadowOffsetY = 8

  // Card background
  ctx.beginPath()
  ctx.moveTo(CX + R, CY)
  ctx.lineTo(CX + CW - R, CY)
  ctx.quadraticCurveTo(CX + CW, CY, CX + CW, CY + R)
  ctx.lineTo(CX + CW, CY + CH - R)
  ctx.quadraticCurveTo(CX + CW, CY + CH, CX + CW - R, CY + CH)
  ctx.lineTo(CX + R, CY + CH)
  ctx.quadraticCurveTo(CX, CY + CH, CX, CY + CH - R)
  ctx.lineTo(CX, CY + R)
  ctx.quadraticCurveTo(CX, CY, CX + R, CY)
  ctx.closePath()
  ctx.fillStyle = '#f5f3ef'
  ctx.fill()
  ctx.shadowColor = 'transparent'

  // Card header stripe
  ctx.fillStyle = '#003B6F'
  ctx.fillRect(CX, CY, CW, 56)

  // Header text
  ctx.fillStyle = '#fff'
  ctx.font = 'bold 15px Arial, sans-serif'
  ctx.textAlign = 'left'
  ctx.fillText('SCHWEIZ · SUISSE · SVIZZERA · SVIZRA', CX + 20, CY + 22)
  ctx.font = '13px Arial, sans-serif'
  ctx.fillStyle = 'rgba(255,255,255,0.75)'
  ctx.fillText('IDENTITY CARD / CARTE D\'IDENTITÉ / CARTA D\'IDENTITÀ', CX + 20, CY + 42)

  // Swiss cross (top right of header)
  const sx = CX + CW - 48, sy = CY + 10
  ctx.fillStyle = '#fff'
  ctx.fillRect(sx + 14, sy, 8, 36)
  ctx.fillRect(sx, sy + 12, 36, 12)

  // ── Photo area ───────────────────────────────────────────────────────────
  const PX = CX + 24, PY = CY + 72, PW = 160, PH = 200
  ctx.fillStyle = '#ccc'
  ctx.fillRect(PX, PY, PW, PH)
  try {
    const imgResp = await fetch('/lea.jpeg')
    const imgBlob = await imgResp.blob()
    const bitmap = await createImageBitmap(imgBlob)
    ctx.drawImage(bitmap, PX, PY, PW, PH)
    bitmap.close()
  } catch { /* photo optional */ }
  // Photo border
  ctx.strokeStyle = '#aaa'
  ctx.lineWidth = 1
  ctx.strokeRect(PX, PY, PW, PH)

  // ── ID fields ────────────────────────────────────────────────────────────
  const FX = CX + 206  // fields left
  let fy = CY + 88

  const field = (label: string, value: string) => {
    ctx.font = '11px Arial, sans-serif'
    ctx.fillStyle = '#003B6F'
    ctx.textAlign = 'left'
    ctx.fillText(label.toUpperCase(), FX, fy)
    ctx.font = 'bold 16px Arial, sans-serif'
    ctx.fillStyle = '#111'
    ctx.fillText(value, FX, fy + 18)
    fy += 46
  }

  field('Surname',          'FONTAINE')
  field('Given names',      'Léa Marie')
  field('Date of birth',    '04.07.1989')
  field('Nationality',      'Swiss')
  field('Document No.',     'F98765432')

  // Second column of fields
  const FX2 = CX + 520
  let fy2 = CY + 88

  const field2 = (label: string, value: string) => {
    ctx.font = '11px Arial, sans-serif'
    ctx.fillStyle = '#003B6F'
    ctx.textAlign = 'left'
    ctx.fillText(label.toUpperCase(), FX2, fy2)
    ctx.font = 'bold 16px Arial, sans-serif'
    ctx.fillStyle = '#111'
    ctx.fillText(value, FX2, fy2 + 18)
    fy2 += 46
  }

  field2('AHV / AVS No.',   '756.4321.8765.03')
  field2('Valid until',     '04.07.2029')
  field2('Place of birth',  'Geneva')
  field2('Address',         'Rue de Rive 14')
  field2('',                '1204 Geneva, Switzerland')

  // ── MRZ zone ────────────────────────────────────────────────────────────
  const MRZ_Y = CY + CH - 80
  ctx.fillStyle = '#e8e4de'
  ctx.fillRect(CX, MRZ_Y, CW, 80)
  ctx.strokeStyle = '#ccc'
  ctx.lineWidth = 1
  ctx.beginPath()
  ctx.moveTo(CX, MRZ_Y)
  ctx.lineTo(CX + CW, MRZ_Y)
  ctx.stroke()
  ctx.font = '13px "Courier New", monospace'
  ctx.fillStyle = '#222'
  ctx.textAlign = 'left'
  ctx.fillText('IDFONTAINE<<LEA<MARIE<<<<<<<<<<<<<<<<<<<<<<<', CX + 20, MRZ_Y + 26)
  ctx.fillText('F987654329CHE8907044F2907044<<<<<<<<<<<<<<<8', CX + 20, MRZ_Y + 50)

  // ── Small label below card ───────────────────────────────────────────────
  ctx.fillStyle = 'rgba(0,0,0,0.4)'
  ctx.font = '11px Arial, sans-serif'
  ctx.textAlign = 'center'
  ctx.fillText('Demo document — all data is fictitious', W / 2, CY + CH + 26)

  // ── PNG → PDF (image-only, no text layer → triggers OCR) ────────────────
  const pngBlob = await canvas.convertToBlob({ type: 'image/png' })
  const pngBytes = await pngBlob.arrayBuffer()

  const pdfDoc = await PDFDocument.create()
  const pngImage = await pdfDoc.embedPng(pngBytes)
  // Landscape page
  const page = pdfDoc.addPage([842, 595])
  page.drawImage(pngImage, { x: 0, y: 0, width: 842, height: 595 })

  const bytes = await pdfDoc.save()
  return new File([bytes.buffer as ArrayBuffer], 'id-card-scan.pdf', { type: 'application/pdf' })
}
